import "react";
import { Container, Row, Col, Button } from "react-bootstrap";
import PropTypes from "prop-types";
import "./Features.css";
import videoCreation from "../assets/video.png";
import videoScripting from "../assets/scripting.png";
import timeEfficiency from "../assets/time.png";
import automation from "../assets/automation.png";
import growAudience from "../assets/grow-audience.png";
import analytics from "../assets/analytics.png";
import useScrollAnimation from "../hooks/useScrollAnimation";

const features = [
  {
    title: "Create Stunning, Faceless Videos with AI",
    description:
      "Utilize advanced AI algorithms to generate high-quality, engaging videos without the need to show your face.",
    image: videoCreation,
  },
  {
    title: "AI Script Generation",
    description:
      "Get your scripts generated by AI, providing you with ready-to-use content tailored to your needs.",
    image: videoScripting,
  },
  {
    title: "Automate Your Social Media Posting",
    description:
      "Schedule and automate your social media posts to ensure consistent and timely content delivery.",
    image: automation,
  },
  {
    title: "Save Time and Effort",
    description:
      "Let our AI handle the heavy lifting of video creation, giving you more time to focus on other important tasks.",
    image: timeEfficiency,
  },
  {
    title: "Grow Your Audience",
    description:
      "Reach a larger audience with our optimized video content designed to maximize engagement and reach.",
    image: growAudience,
  },
  {
    title: "Analytics Insight",
    description:
      "Gain valuable insights into your video performance on social media with detailed analytics and reports.",
    image: analytics,
  },
];

const Features = ({ onJoinWaitlist }) => {
  const [featuresRef, isVisible] = useScrollAnimation();
  return (
    <div
      className={`features-section features ${isVisible ? "slide-up" : ""}`}
      ref={featuresRef}
    >
      <Container className="py-5 px-5">
        <Row className="text-center">
          <Col>
            <h2 className="features-title">Our Features</h2>
            <p className="features-subtitle">
              Discover what SpreadHit can do for you
            </p>
          </Col>
        </Row>
        {features.map((feature, index) => (
          <Row
            key={index}
            className={`feature-row ${
              index % 2 === 0 ? "flex-row-reverse" : ""
            }`}
          >
            <Col md={6} className="feature-image-col">
              <img
                src={feature.image}
                alt={feature.title}
                className="img-fluid feature-image"
              />
            </Col>
            <Col md={6} className="feature-details-col">
              <h3 className="feature-title">{feature.title}</h3>
              <p className="feature-description">{feature.description}</p>
            </Col>
          </Row>
        ))}
        <div className="d-flex justify-content-center">
          <Button variant="info" className="mt-5 px-5" onClick={onJoinWaitlist}>
            Join Waitlist
          </Button>
        </div>
      </Container>
    </div>
  );
};

Features.propTypes = {
  onJoinWaitlist: PropTypes.func.isRequired,
};

export default Features;
